# Generated by Django 4.1.3 on 2022-12-01 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_converter', '0002_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
